[meta]
version = 6

[executables]
conjure = /usr/bin/conjure-client
meek_lite = /usr/bin/meek-lite
obfs4 = /usr/bin/obfs4proxy
snowflake = /usr/bin/snowflake-client
webtunnel = /usr/bin/webtunnel-client

[conjure]
🔮🌳🌙🫒 = conjure 143.110.214.222:80 url=https://registration.refraction.network.global.prod.fastly.net/api front=cdn.sstatic.net

[meek_lite]
🐵🥖🦉⚖️ = meek_lite 192.0.2.18:80 BE776A53492E1E044A26F17306E1BC46A55A1625 url=https://meek.azureedge.net/ front=ajax.aspnetcdn.com

[obfs4]
🐌🦓🎸🦈 = obfs4 103.158.223.120:5388 94ACF8D218505628B469C2017C6B2A4735474D6F cert=T6CJHxD51mIuwlUAsEQJK+uSLzukjhUJt0AnjqDY3veKZXPfNgTRDq7i6mhH8KrAbWYFNg iat-mode=0
🦈🏝️🐪🎏 = obfs4 87.62.98.28:9003 150530E71DF116D514AF6E04C2EC18F16803FF72 cert=zJVQ+C2X5SndHqKgsYqT4vOexUqg4zFpyBwdtmKLM7CU6ceDFQk6uijsC1FCIFrCblFBAw iat-mode=0
💿️🏷️🐥🖍️ = obfs4 157.180.66.181:7314 FC0C482D2A0BA0D8408797714915715CBE19FFD7 cert=32ijRT72SAdmLcv4uI/6T6OK71Oo/ILiJWn+uEWOxmxHvZ2saY6g7hNHAR/yR04JKcQ5Og iat-mode=0
🐘⚽️🥏🍁 = obfs4 162.55.219.253:21358 A43C6D5A85CE5D52486293C507983409ED7C1EC0 cert=t0TUwf8Gu+jz8nxWYAPR/VMqh9k8+efrZFTIg6HNpitEdNH1fT1KlAz51jAZqxQq8/9nEA iat-mode=0

[snowflake]
🍅🧁🛹🍅 = snowflake 192.0.2.3:80 2B280B23E1107BB62ABFC40DDCC8824814F80A72 fingerprint=2B280B23E1107BB62ABFC40DDCC8824814F80A72 url=https://1098762253.rsc.cdn77.org/ fronts=app.datapacket.com,www.datapacket.com ice=stun:stun.epygi.com:3478,stun:stun.uls.co.za:3478,stun:stun.voipgate.com:3478,stun:stun.mixvoip.com:3478,stun:stun.telnyx.com:3478,stun:stun.hot-chilli.net:3478,stun:stun.fitauto.ru:3478,stun:stun.m-online.net:3478 utls-imitate=hellorandomizedalpn
✨⛲️🤿💧 = snowflake 192.0.2.4:80 8838024498816A039FCBBAB14E6F40A0843051FA fingerprint=8838024498816A039FCBBAB14E6F40A0843051FA url=https://1098762253.rsc.cdn77.org/ fronts=app.datapacket.com,www.datapacket.com ice=stun:stun.epygi.com:3478,stun:stun.uls.co.za:3478,stun:stun.voipgate.com:3478,stun:stun.mixvoip.com:3478,stun:stun.telnyx.com:3478,stun:stun.hot-chilli.net:3478,stun:stun.fitauto.ru:3478,stun:stun.m-online.net:3478 utls-imitate=hellorandomizedalpn
🐝🕊️🦇🦦 = snowflake 192.0.2.5:80 2B280B23E1107BB62ABFC40DDCC8824814F80A72 fingerprint=2B280B23E1107BB62ABFC40DDCC8824814F80A72 url=https://snowflake-broker.torproject.net/ ampcache=https://cdn.ampproject.org/ front=www.google.com ice=stun:stun.antisip.com:3478,stun:stun.epygi.com:3478,stun:stun.uls.co.za:3478,stun:stun.voipgate.com:3478,stun:stun.mixvoip.com:3478,stun:stun.nextcloud.com:3478,stun:stun.bethesda.net:3478,stun:stun.nextcloud.com:443 utls-imitate=hellorandomizedalpn
🚍️🎷🥞❄️ = snowflake 192.0.2.6:80 8838024498816A039FCBBAB14E6F40A0843051FA fingerprint=8838024498816A039FCBBAB14E6F40A0843051FA url=https://snowflake-broker.torproject.net/ ampcache=https://cdn.ampproject.org/ front=www.google.com ice=stun:stun.antisip.com:3478,stun:stun.epygi.com:3478,stun:stun.uls.co.za:3478,stun:stun.voipgate.com:3478,stun:stun.mixvoip.com:3478,stun:stun.nextcloud.com:3478,stun:stun.bethesda.net:3478,stun:stun.nextcloud.com:443 utls-imitate=hellorandomizedalpn
#🍔🧁🦦🐶 = snowflake 192.0.2.5:80 2B280B23E1107BB62ABFC40DDCC8824814F80A72 fingerprint=2B280B23E1107BB62ABFC40DDCC8824814F80A72 sqsqueue=https://sqs.us-east-1.amazonaws.com/893902434899/snowflake-broker sqscreds=eyJhd3MtYWNjZXNzLWtleS1pZCI6IkFLSUE1QUlGNFdKSlhTN1lIRUczIiwiYXdzLXNlY3JldC1rZXkiOiI3U0RNc0pBNHM1RitXZWJ1L3pMOHZrMFFXV0lsa1c2Y1dOZlVsQ0tRIn0= ice=stun:stun.antisip.com:3478,stun:stun.epygi.com:3478,stun:stun.uls.co.za:3478,stun:stun.voipgate.com:3478,stun:stun.nextcloud.com:3478,stun:stun.bethesda.net:3478,stun:stun.nextcloud.com:443 utls-imitate=hellorandomizedalpn
#🚠🛹🍄🌵 = snowflake 192.0.2.6:80 8838024498816A039FCBBAB14E6F40A0843051FA fingerprint=8838024498816A039FCBBAB14E6F40A0843051FA sqsqueue=https://sqs.us-east-1.amazonaws.com/893902434899/snowflake-broker sqscreds=eyJhd3MtYWNjZXNzLWtleS1pZCI6IkFLSUE1QUlGNFdKSlhTN1lIRUczIiwiYXdzLXNlY3JldC1rZXkiOiI3U0RNc0pBNHM1RitXZWJ1L3pMOHZrMFFXV0lsa1c2Y1dOZlVsQ0tRIn0= ice=stun:stun.antisip.com:3478,stun:stun.epygi.com:3478,stun:stun.uls.co.za:3478,stun:stun.voipgate.com:3478,stun:stun.nextcloud.com:3478,stun:stun.bethesda.net:3478,stun:stun.nextcloud.com:443 utls-imitate=hellorandomizedalpn

[vanilla]
⏰🚚🎡🦌 = 82.65.123.107:9001 5105C5FD49A1A8DEF6CD754F7657BDA13BA2A3FE
🐠🎙️🥥🪕 = 45.131.66.223:9001 F65F739E5B297813C16C99D631B28EAFAC2383C3
🦋💡🎏🏝️ = 87.118.88.48:4711 522814C15B47827EB0BBE2939AF3133BB6D34769
🦊🍑🎶🎲 = 72.18.53.189:9321 CED88BFBA5465E84E81F827B5BB90E1F7D45BD62

[webtunnel]
🌵🐴🦉🦉 = webtunnel [2001:db8:582a:3e92:df7a:c770:19f7:64e0]:443 67313AEAF0319B172CD12EAEAFCD6F29C12171AB url=https://tor-bridge.scaledra.com/Cgb29jTFCUBdTGEz8BDkQFrn ver=0.0.4
🔑🦩🦧🐱 = webtunnel [2001:db8:bce8:edf7:7b33:480b:fde5:4840]:443 A417275864EA76F47CEAD4071273D82917283A12 url=https://www3.ruhnama.net/Ly4uulgoy2LWmMX3fk007Gme ver=0.0.3
🥨🦇🥦🐟️ = webtunnel [2001:db8:e65a:afaf:7443:b5a5:f71d:ca4]:443 6FE31638D6084EDA6D94FADC99B0EDD109D6AE3A url=https://eu.g3wip.uk/7ePavP0vnTTelEJWeJ4NwpGE ver=0.0.1
🎾🥯💐🌙 = webtunnel [2001:db8:603c:2434:873c:4d58:9fd0:91e0]:443 56626E4B996EB1C9F4C0B573888E8EE3C4E28472 url=https://kriptohomyaki.org/4USXwPrEoemgJOXPmgjxPOAkQa1UG7To ver=0.0.3

[hidden-service-ports]
web = 80 127.0.0.1:8080
ssh = 22 127.0.0.1:22
